[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true         # 必须开启
optimizer_runs = 10 # 设置更高的优化等级

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]


[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
